name: Java Selenium Automation workflow with Maven

on: 
  schedule:
    - cron: 00 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    # Run tests with Maven
    - name: Run Selenium Tests
      run: mvn test -Dbrowser=chrome -DisHeadLess=false -DisLambdaTest=false

    # Upload logs
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: Test Logs
        path: logs/

    # Upload HTML report
    - name: Upload Extent Report
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: Extent Report
        path: ExtentReports/report.html

    - name: Test Execution Status
      run: echo "Test Execution Completed"
