name: Java Selenium Automation workflow with Maven

on: 
  schedule:
  - cron: 00 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Running the tests with Maven
      run: mvn test -Dbrowser=edge -DisHeadLess=false -DisLambdaTest=false 

    - name: Upload logs of the test
      if: always()
      uses: actions/upload-artifact@v5.0.0
      with:
        name: Test Logs
        path: logs/

    - name: Upload Extent Test Report
      if: always()
      uses: actions/upload-artifact@v5.0.0
      with:
        name: Extent Reports
        path: ExtentReports/report.html

    - name: Test Execution Status
      run: echo "Test Execution Completed"
      

    
    


